apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jhx2vf2fu-python
  janus-idp.io/tekton: jhx2vf2fu-python
  backstage.io/kubernetes-id: jhx2vf2fu-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jhx2vf2fu-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
