apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: jhx2vf2fu-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jhx2vf2fu-python 
  name: jhx2vf2fu-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: jhx2vf2fu-python
    weight: 100 
