apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jhx2vf2fu-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jhx2vf2fu-python 
  name: jhx2vf2fu-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jhx2vf2fu-python 
